visgl/loaders.gl-showcases

src/components/attributes-panel/attributes-panel.tsx, src/components/tile-validator/tile-validator.tsx
=> fix(attributes-panel): change layout and font sizes

src/utils/colors-map.spec.ts
=> chore(colorMap): add unit tests

src/utils/url-utils.spec.ts
=> test(unit): url-utils

babel.config.js, package.json, src/components/attributes-panel/attributes-panel.spec.tsx, yarn.lock
Setup first unit test for react component
=> test(unit): setup unit tests for react components

src/pages/dashboard/dashboard.tsx
https://be4ep5ynhp1v5kxx.maps.arcgis.com/home/webscene/viewer.html?layers=7c5bea23fce946d0905a926c32931ec0
=> feat(dashboard): change dataset

src/pages/debug-app/debug-app.tsx, src/pages/viewer-app/viewer-app.tsx
=> chore(statistics): add formatter for tile memory use

src/app.tsx, src/components/header/header.tsx, src/pages/dashboard/e2e.dashboard.spec.ts, src/pages/index.ts
=> feat(header): add compare tab for default view

src/components/action-button/action-button.tsx, src/types.ts
=> feact(actionButton): add component

src/app.tsx, src/components/input-text/input-text.spec.tsx, src/components/input-text/input-text.tsx, src/utils/testing-utils/render-with-theme.spec.tsx, src/utils/testing-utils/render-with-theme.tsx
=> feat(input-text): add component

src/components/layers-panel/layer-settings-menu.tsx, src/components/layers-panel/layers-control-panel.tsx, src/components/layers-panel/layers-panel.tsx, src/pages/comparison/comparison.tsx
Straightforward approach.
We need to refactor "page" components. A lot of logic is copy-pasted.
=> feat(compare): load layers

src/components/help-panel/shotrcuts-config.tsx
=> fix(help-panel): change panning icon

src/components/comparison/comparison-side/comparison-side.spec.tsx, src/components/comparison/comparison-side/comparison-side.tsx, src/pages/comparison/comparison.tsx, src/pages/comparison/e2e.comparison.spec.ts
* compare button logic has been changed
* comparing is disabled till all tiles of current viewState are loaded
=> fix(compare): disable till all tiles are loaded

src/components/comparison/comparison-side/comparison-side.tsx
**`findExampleAndUpdateWithTileset`** -> **`findExampleAndUpdateWithViewState`**
=> chore(comparison): rename method 

package.json, src/components/comparison/comparison-side/comparison-side.tsx, src/components/comparison/memory-usage-panel/memory-usage-panel.spec.tsx, src/components/comparison/memory-usage-panel/memory-usage-panel.tsx, src/components/debug/tile-metadata/tile-metadata.tsx, src/components/debug/tile-tooltip/tile-tooltip.tsx, src/types.ts, src/utils/format/format-utils.spec.ts, src/utils/format/format-utils.ts, yarn.lock
=> feat(stats): content formats

package.json, src/components/comparison/comparison-side/comparison-side.tsx, src/components/comparison/layers-panel/layers-panel.spec.tsx, src/components/comparison/layers-panel/layers-panel.tsx, src/components/deck-gl-wrapper/deck-gl-wrapper.tsx, src/constants/i3s-examples.ts, src/pages/comparison/comparison.tsx, src/utils/bookmarks-utils.spec.ts, src/utils/bookmarks-utils.ts, src/utils/elevation-utils.spec.ts, src/utils/elevation-utils.ts, src/utils/layer-utils.spec.ts, src/utils/layer-utils.ts, yarn.lock
Types are added here - https://github.com/visgl/loaders.gl/pull/2299
=> chore(comparison): add webscene bookmarks support

src/components/debug-panel/debug-panel.spec.tsx, src/components/debug-panel/debug-panel.tsx, src/pages/debug-app/debug-app.tsx, src/types.ts
- Save debug options in bookmarks
- Code refactoring
=> chore(debug): Save debug options in bookmarks

src/pages/debug-app/debug-app.tsx, src/pages/viewer-app/viewer-app.tsx
Also fix "rotate/pan works affter second click" issue
=> chore(viewer,debug): fix rotate/pan modes switching

src/components/comparison/comparison-side/comparison-side.tsx, src/components/layers-panel/layers-panel.tsx, src/utils/bookmarks-utils.ts
=> fix: ArcGIS slides to bookmark zoom conversion

src/components/attributes-panel/attributes-stats/attribute-stats.spec.tsx, src/components/attributes-panel/attributes-stats/attribute-stats.tsx, src/components/deck-gl-wrapper/deck-gl-wrapper.spec.tsx, src/components/deck-gl-wrapper/deck-gl-wrapper.tsx, src/types.ts
=> feat: Add an option to multiply colors by attribute

src/components/deck-gl-wrapper/deck-gl-wrapper.tsx, src/redux/slices/uv-debug-texture-slice.tsx, src/redux/store.tsx
=> chore: Move async debug texture loading to redux

src/components/comparison/comparison-side/comparison-side.tsx, src/pages/comparison/comparison.tsx, src/pages/debug-app/debug-app.tsx, src/pages/viewer-app/viewer-app.tsx, src/redux/slices/flattened-sublayers-slice.tsx
=> chore: Move compare mode sublayers to redux

src/components/layers-panel/list-item-wrapper/list-item-wrapper.tsx, src/components/layers-panel/list-item/list-item.tsx, src/components/radio-button/radio-button.tsx
=> fix: Long names in the layers options
